name: qstash_dart
description: QStash is an HTTP based messaging and scheduling solution for serverless and edge runtimes.
version: 2.0.0
homepage: https://github.com/rebaz94/qstash_dart
issue_tracker: https://github.com/upstash/sdk-qstash-ts/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
