name: qstash_dart
description: QStash is an HTTP based messaging and scheduling solution for serverless and edge runtimes.
version: 1.0.1
homepage: https://github.com/rebaz94/qstash_dart
issue_tracker: https://github.com/upstash/sdk-qstash-ts/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.5
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
